#!/usr/bin/env bash
# Configures a ufw firewall to block alll incoming traffic
# except TCP ports 22, 80 and 443.

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
